# Generated by Django 3.1 on 2020-09-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200830_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
