# Generated by Django 3.1 on 2020-09-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='username',
        ),
    ]
